language: rust
rust: stable
install:
    - curl -Ls https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz | tar xzf - -C .
    - git clone --depth 1 https://github.com/vim-airline/vim-airline.git
    - rustup component add clippy-preview
    - rustup component add rustfmt-preview
before_script:
    - uname -a
    - vim --version
    - nvim-linux64/bin/nvim --version
    - cd vim-airline && git rev-parse HEAD && cd -
script:
    - bash .ci/run-cargo-checks.bash
    - vim -E -c 'set t_Co=256 rtp+=.,./vim-airline | runtime plugin/airline.vim' -c 'try | colorscheme spring-night | AirlineTheme spring_night | catch | cquit | endtry' -c 'quit'
    - nvim-linux64/bin/nvim -E -c 'set t_Co=256 termguicolors rtp+=.,./vim-airline | runtime plugin/airline.vim' -c 'try | colorscheme spring-night | AirlineTheme spring_night | catch | cquit | endtry' -c 'quit'
    - bash .ci/colorscheme-file-is-latest.bash
